# Generated by Django 5.0.1 on 2024-02-21 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Category_name",
        ),
    ]
