# Generated by Django 5.0.1 on 2024-02-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_remove_story_appreciation_rating_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="rating",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0
            ),
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
