# Generated by Django 5.0.1 on 2024-02-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
