# Generated by Django 5.0.1 on 2024-02-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mywords",
            name="word",
            field=models.CharField(max_length=100),
        ),
    ]
